name: inbox_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_verification_code: ^1.1.6
  http: 0.13.5
  flutter_secure_storage: ^8.0.0
  socket_io_client: ^2.0.1
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  rxdart: ^0.27.7
  path_provider: ^2.0.13
  local_auth: ^2.1.6
  permission_handler: ^10.2.0
  mic_stream: ^0.6.4
  flutter_mjpeg: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

flutter:
  uses-material-design: true

  assets:
    - assets/img/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo.png"
